psql -d jobs <users.pgsql
psql -d jobs <states.sql
psql -d jobs <degreetypes.sql
psql -d jobs <jobclasses.sql
psql -d jobs <profiles.sql
psql -d jobs <education.sql
psql -d jobs <employers.sql
psql -d jobs <personality.pgsql
psql -d jobs <jobs.pgsql
#psql -d jobs <filler.pgsql
